language: python

sudo: false

python:
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'
  - 'pypy'

addons:
  apt:
    packages:
      - trang

install:
  - pip install lxml
  - pip install nose

  - cd ..
  - hg clone https://bitbucket.org/bdarcus/citeproc-test
  - cd citeproc-test
  - python processor.py -g
  - cd ..

  - cd citeproc-py
  - trang -I rnc -O rng citeproc/data/schema/csl.rnc citeproc/data/schema/csl.rng

script:
  - nosetests
  - PYTHONPATH="." python tests/citeproc-test.py
