language: python

sudo: false

python:
  - '2.7'
  - '3.2'
  - '3.3'
  - '3.4'
  - '3.5'

install:
  - pip install rnc2rng tox-travis
  - rnc2rng citeproc/data/schema/csl.rnc citeproc/data/schema/csl.rng

script:
  - tox
