name: Test

on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - macos-latest
          - windows-latest
        python-version:
          - '2.7'
          - '3.5'
          - '3.6'
          - '3.7'
          - '3.8'
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install --upgrade --upgrade-strategy=eager tox tox-gh-actions

      - name: Run tests
        run: tox
        env:
          # Needed for coveralls:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# vim:set et sts=2:
